/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srikanth
 */
public class Profile_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Profile_Page() {
        initComponents();
        viewtable();
    }
    String user;
    HomePage page;

    public Profile_Page(String user, HomePage page) {
        this.user = user;
        this.page = page;
        initComponents();
        viewtable();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display_Table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        F_Name_var = new javax.swing.JTextField();
        L_Name_var = new javax.swing.JTextField();
        Ph_var = new javax.swing.JTextField();
        Add_var = new javax.swing.JTextField();
        Pass_var = new javax.swing.JTextField();
        Update_Button = new javax.swing.JButton();
        Logout_Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Product Name", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Display_Table);

        jLabel3.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel3.setText("Recent Orders");

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel2.setText("Update Profile");

        F_Name_var.setBackground(new java.awt.Color(214, 217, 223));
        F_Name_var.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        F_Name_var.setText("First Name");
        F_Name_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        F_Name_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_Name_varActionPerformed(evt);
            }
        });

        L_Name_var.setBackground(new java.awt.Color(214, 217, 223));
        L_Name_var.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        L_Name_var.setText("Last Name");
        L_Name_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        L_Name_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_Name_varActionPerformed(evt);
            }
        });

        Ph_var.setBackground(new java.awt.Color(214, 217, 223));
        Ph_var.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Ph_var.setText("Phone Number");
        Ph_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Ph_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ph_varActionPerformed(evt);
            }
        });

        Add_var.setBackground(new java.awt.Color(214, 217, 223));
        Add_var.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Add_var.setText("Address");
        Add_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_varActionPerformed(evt);
            }
        });

        Pass_var.setBackground(new java.awt.Color(214, 217, 223));
        Pass_var.setFont(new java.awt.Font("Product Sans", 0, 13)); // NOI18N
        Pass_var.setText("Password");
        Pass_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Pass_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_varActionPerformed(evt);
            }
        });

        Update_Button.setText("Update");
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });

        Logout_Button1.setText("Logout");
        Logout_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Back_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout_Button1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Update_Button)
                            .addComponent(F_Name_var, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Name_var, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ph_var, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_var, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pass_var, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(460, 460, 460))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_Button)
                    .addComponent(Logout_Button1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(F_Name_var, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L_Name_var, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ph_var, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add_var, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pass_var, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Update_Button)))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_Button1ActionPerformed
        // K Srikanth 17ETCS002124
        JOptionPane.showMessageDialog(this, "You have been logged out sucessfully");
        Login someobj = new Login();
        someobj.setVisible(true);
    }//GEN-LAST:event_Logout_Button1ActionPerformed

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        // K Srikanth 17ETCS002124
        String First_Name;
        String Last_Name;
        String Phone_Number;
        String Address;
        String Password;

        First_Name = F_Name_var.getText();
        Last_Name = L_Name_var.getText();
        Address = Add_var.getText();
        Phone_Number = Ph_var.getText();
        Password = Pass_var.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment", "root", "Sri123");
            pst = con.prepareStatement("update user set First_Name = ?,Last_Name = ?,Phone_Number = ? ,Address = ? , Password= ? where Phone_Number = ?");
            pst.setString(1, First_Name);
            pst.setString(2, Last_Name);
            pst.setString(3, Phone_Number);
            pst.setString(4, Address);
            pst.setString(5, Password);
            pst.setString(6, Phone_Number);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Hey, " + First_Name + " Your Account has been Updated.");
            F_Name_var.setText("First Name");
            L_Name_var.setText("Last Name");
            Add_var.setText("Address");
            Ph_var.setText("Phone Number");
            Pass_var.setText("Password");
            F_Name_var.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Profile_Page.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(Profile_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Update_ButtonActionPerformed


    private void Pass_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_varActionPerformed

    private void Add_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_varActionPerformed

    private void Ph_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ph_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ph_varActionPerformed

    private void L_Name_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_Name_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_Name_varActionPerformed

    private void F_Name_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_Name_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_Name_varActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        // K Srikanth 17ETCS002124
        HomePage someobj = new HomePage();
        someobj.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Page().setVisible(true);
            }
        });
    }

    public void viewtable() {
        // K Srikanth 17ETCS002124
        int c;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment", "root", "Sri123");
            pst = con.prepareStatement("select * from orders join product where product.product_id=orders.product_id and orders.User_ID = ?");
            pst.setString(1, user);
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) Display_Table.getModel();
            dft.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i < c; i++) {
                    v2.add(rs.getString("Order_ID"));
                    v2.add(rs.getString("Product_Name"));
                    v2.add(rs.getObject("Date_Time"));
                }
                dft.addRow(v2);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add_var;
    private javax.swing.JButton Back_Button;
    private javax.swing.JTable Display_Table;
    private javax.swing.JTextField F_Name_var;
    private javax.swing.JTextField L_Name_var;
    private javax.swing.JButton Logout_Button1;
    private javax.swing.JTextField Pass_var;
    private javax.swing.JTextField Ph_var;
    private javax.swing.JButton Update_Button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
